[output]
format = "colored-line-number"

[linters]
enable = [
    # Visit https://golangci-lint.run/usage/linters/
    # for the full, current list of available linters.

    # Default linters
    "deadcode", # Finds unused code
    "errcheck", # Detect unchecked errors
    "gosimple", # Suggest code simplifications
    "govet", # Reports suspicious constructs
    "ineffassign", # Detects unused variable assignments
    "staticcheck", # go vet on steroids
    "structcheck", # Find unused struct fields
    "typecheck", # Standard Go type checks
    "unused", # Detect unused constants, variables, functions and types
    "varcheck", # Find unused global variables and constants

    # Suggested additional linters
    "gocyclo", # or "cyclop", # Detect cyclomatic complexity
    "goconst", # Detect repeated values that can be made constants
    "gofumpt", # Or "gofmt", # Enforce standard formatting
    "goimports", # Ensure standard import formatting/ordering
    "misspell", # Fix spelling errors
    # "revive",  # General purpose linter
    "unconvert", # Detect unnecessary type conversions
    "unparam", # Detect unused function parameters
]

[issues]
exclude-use-default = false