name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
        run: go version

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test
        run: make coverage
